language: php
sudo: false
php:
  - 7.2
  - 7.3
env:
  - SYMFONY_VERSION=~2.7
  - SYMFONY_VERSION=~3.0
  - SYMFONY_VERSION=~4.0

before_install:
  - composer require --no-update symfony/console $SYMFONY_VERSION
  - composer require --no-update symfony/dependency-injection $SYMFONY_VERSION
  - composer require --no-update symfony/config $SYMFONY_VERSION
  - composer require --no-update symfony/yaml $SYMFONY_VERSION
  - composer require --no-update symfony/finder $SYMFONY_VERSION
  - composer require --no-update symfony/filesystem $SYMFONY_VERSION
  - composer require --no-update symfony/event-dispatcher $SYMFONY_VERSION

install:
  - composer install --prefer-dist

script:
  - ./typoscript-lint --help
  - bin/phpunit --coverage-clover build/logs/clover.xml
  - bin/phan -z -S --allow-polyfill-parser

after_success:
  - bin/test-reporter
