name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: olegtarasov/get-tag@j1
        id: tagName

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Build PHAR
        run: composer run-script package ${{ steps.tagName.outputs.tag }}
        env:
          signing_key: ${{ secrets.pharSigningKey }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            typoscript-lint-*.phar
            typoscript-lint-*.phar.asc
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
