name: Build PHAR for release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Build PHAR
        run: composer run-script package ${{ steps.tagName.outputs.tag }}
        env:
          signing_key: ${{ secrets.pharSigningKey }}
          signing_key_fingerprint: ${{ secrets.PHAR_SIGNING_KEY_FINGERPRINT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            typoscript-lint-*.phar
            typoscript-lint-*.phar.asc
        env:
          GITHUB_TOKEN: ${{ github.token }}
